### ISSUE TITLE
runs ok on localhost, but no results after 15 min on the cloud

### ISSUE THREAD

**Issue by robert-s-lee** [Nachimak28/evidently-data-analysis#3] opened 2022-08-23 14:22 UTC
perhaps the default 1 CPU is not enough on the cloud to make progress.

**Comment by Nachimak28** [comment] 2022-08-23 14:31
Exactly, I've been facing the same problem and hence haven't confirmed with the team on the submission to the gallery. I've been meaning to ask about this in the slack channel but might just solve it here.

As seen in the logs, the html file which is the desired output format for this component does get generated successfully but it simply doesn't show up in the browser.

Would passing L.CloudCompute("cpu-small") to any of the work components help? 
I can probably test this out with some trial and error.

**Comment by robert-s-lee** [comment] 2022-08-23 15:25
I tried 8xCPUs but the same.  Let me look at the code a bit and see what is going on.

**Comment by Nachimak28** [comment] 2022-08-23 15:40
I tried looking at the network calls and seeing a 404 error for the report_render request. 
report_render is the object of StaticWebPage viewer component (LitFlow) in my app.py which inturn uses StaticWebFrontend to display the index.html generated by evidently work component. Am I using the StaticWebFrontend in a wrong way?

I even added a simple StaticWebFrontend component directly in the configure_layout function of the main component of the app. Still getting a similar 404 error. Could this be because of the time taken by evidently to build the dashboard?


![Screen Shot 2022-08-23 at 8 50 53 PM](https://user-images.githubusercontent.com/23210132/186197751-d0c575cf-cc8b-4589-b55f-ca4b1e7e3b99.png)

**Comment by robert-s-lee** [comment] 2022-08-23 20:44
LightningWork and Flow cannot exchange files.  Changed to use Flask inside the Work.

**Comment by Nachimak28** [comment] 2022-08-24 13:09
Ah, my bad - shall read the docs more carefully next time. Thank you so much for creating the PR and fixing the issue. Everything worked out perfectly in the cloud. Also really sorry if you had to spend too much time on it. 

Closing this issue now

**Closed as completed by Nachimak28** 2022-08-24 13:09 UTC
